version: '3.9'

services:
  db:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
