spring:
  application.name: gateway

  cloud:
    gateway:
      enabled:
        true
      routes:
        - id: create-task
          uri: http://localhost:8081
          predicates:
            - Path=/task

        - id: static-resources
          uri: http://localhost:8081
          predicates:
            - Path=/styles.css

        - id: registration
          uri: http://localhost:8082
          predicates:
            - Path=/login, /register

  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: gateway
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gateway
            scope: profile
        provider:
          gateway:
            authorization-uri: http://localhost:8082/oauth2/authorize
            token-uri: http://localhost:8082/oauth2/token
            ##user-info-uri: http://localhost:8082/userinfo
            jwk-set-uri: http://localhost:8082/oauth2/jwks
            ##user-name-attribute: sub

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
