spring:
  application.name: registration
  datasource:
    url: jdbc:postgresql://localhost:5434/registration
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081