spring:
  application.name: registration
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/registration
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082