spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/task-manager
    username: user
    password: password

  application.name: createTask
  sql:
    init:
      mode: always

server:
  port: 8081