spring:
  application.name: createTask
  datasource:
    url: jdbc:postgresql://localhost:5433/task-manager
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update